In [31]:
import pandas as pd
import numpy as np
import pubchempy as pc
import time

# PPARG

In [56]:
df_PPARG = pd.read_table('dataset/BindingDB/PPARG.tsv')

In [57]:
df_PPARG = df_PPARG[['PubChem CID', 'UniProt (SwissProt) Recommended Name of Target Chain']]

In [58]:
df_PPARG = df_PPARG.rename(columns={'UniProt (SwissProt) Recommended Name of Target Chain': 'Protein Target'})

In [59]:
df_PPARG

      PubChem CID                                    Protein Target
0        16110418  Peroxisome proliferator-activated receptor gamma
1        16110511  Peroxisome proliferator-activated receptor gamma
2        16110419  Peroxisome proliferator-activated receptor gamma
3        16110512  Peroxisome proliferator-activated receptor gamma
4        16110420  Peroxisome proliferator-activated receptor gamma
...           ...                                               ...
6885     54325967  Peroxisome proliferator-activated receptor gamma
6886       447458  Peroxisome proliferator-activated receptor gamma
6887      9888484  Peroxisome proliferator-activated receptor gamma
6888       208901  Peroxisome proliferator-activated receptor gamma
6889       206044  Peroxisome proliferator-activated receptor gamma

[6890 rows x 2 columns]

In [60]:
df_PPARG['Protein Target'].value_counts()

Peroxisome proliferator-activated receptor gamma    6890
Name: Protein Target, dtype: int64

In [61]:
#change value 
df_PPARG['Protein Target'] = df_PPARG['Protein Target'].replace(['Peroxisome proliferator-activated receptor gamma'],'PPARG')

In [62]:
df_PPARG

      PubChem CID Protein Target
0        16110418          PPARG
1        16110511          PPARG
2        16110419          PPARG
3        16110512          PPARG
4        16110420          PPARG
...           ...            ...
6885     54325967          PPARG
6886       447458          PPARG
6887      9888484          PPARG
6888       208901          PPARG
6889       206044          PPARG

[6890 rows x 2 columns]

In [63]:
# Remove all duplicate rows 
df_PPARG = df_PPARG.drop_duplicates(keep='first')

In [64]:
df_PPARG

      PubChem CID Protein Target
0        16110418          PPARG
1        16110511          PPARG
2        16110419          PPARG
3        16110512          PPARG
4        16110420          PPARG
...           ...            ...
6880     71452270          PPARG
6881     71462957          PPARG
6882     71462958          PPARG
6883     71462959          PPARG
6884     71461221          PPARG

[4477 rows x 2 columns]

# EP300

In [49]:
df_EP300 = pd.read_table('dataset/BindingDB/EP300.tsv')

In [50]:
df_EP300 = df_EP300[['PubChem CID', 'UniProt (SwissProt) Entry Name of Target Chain']]

In [52]:
df_EP300 = df_EP300.rename(columns={'UniProt (SwissProt) Entry Name of Target Chain': 'Protein Target'})

In [53]:
df_EP300

     PubChem CID Protein Target
0       91935555    EP300_HUMAN
1       91898905    EP300_HUMAN
2       91898906    EP300_HUMAN
3       91898907    EP300_HUMAN
4       91898908    EP300_HUMAN
..           ...            ...
544    134139020      CBP_HUMAN
545    121365442      CBP_HUMAN
546    121372990      CBP_HUMAN
547    134157699      CBP_HUMAN
548    121373032      CBP_HUMAN

[549 rows x 2 columns]

In [55]:
df_EP300['Protein Target'].value_counts()

EP300_HUMAN    401
CBP_HUMAN      132
HIF1A_HUMAN     16
Name: Protein Target, dtype: int64

In [70]:
# selecting rows based which is contains EP300_HUMAN
df_EP300 = df_EP300.loc[df_EP300['Protein Target'].isin(['EP300_HUMAN'])]

In [71]:
df_EP300

     PubChem CID Protein Target
0       91935555    EP300_HUMAN
1       91898905    EP300_HUMAN
2       91898906    EP300_HUMAN
3       91898907    EP300_HUMAN
4       91898908    EP300_HUMAN
..           ...            ...
495      9992116    EP300_HUMAN
496     53257845    EP300_HUMAN
497     76853637    EP300_HUMAN
498      2221149    EP300_HUMAN
499    162669822    EP300_HUMAN

[401 rows x 2 columns]

In [72]:
# Remove all duplicate rows 
df_EP300 = df_EP300.drop_duplicates(keep='first')

In [73]:
df_EP300

     PubChem CID Protein Target
0       91935555    EP300_HUMAN
1       91898905    EP300_HUMAN
2       91898906    EP300_HUMAN
3       91898907    EP300_HUMAN
4       91898908    EP300_HUMAN
..           ...            ...
490    162658719    EP300_HUMAN
491        19009    EP300_HUMAN
492        73061    EP300_HUMAN
496     53257845    EP300_HUMAN
499    162669822    EP300_HUMAN

[319 rows x 2 columns]