In [33]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [54]:
fp = pd.read_csv('../data/com-train-fp.csv')
fp.columns = ['drug', 'pubchemID'] + ['fp_' + str(i) for i in range(881)]
print(fp.shape)
fp.head()

(7708, 883)

,drug,pubchemID,fp_0,fp_1,fp_2,fp_3,fp_4,fp_5,fp_6,fp_7,...,fp_871,fp_872,fp_873,fp_874,fp_875,fp_876,fp_877,fp_878,fp_879,fp_880
0,"4-phenylimidazole, 17",24853793,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"4-phenylimidazole, 19",11700059,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AC1OCG0B,6918878,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Acetyldinaline,2746,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,apicidin,467801,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [55]:
interactions = pd.read_csv('../data/train-interactions.csv')
print(interactions.shape)
interactions.head()

(131036, 4)

   Unnamed: 0   uniprot_id  pubchemID  interaction
0           0  HDAC3_HUMAN   24853793            1
1           1  HDAC3_HUMAN   11700059            1
2           2  HDAC3_HUMAN    6918878            1
3           3  HDAC3_HUMAN       2746            1
4           4  HDAC3_HUMAN     467801            1

# FP-AAC

In [56]:
aac = pd.read_csv('../data/prot-aac.csv')
aac.head()

,aac_1,aac_2,aac_3,aac_4,aac_5,aac_6,aac_7,aac_8,aac_9,aac_10,...,aac_12,aac_13,aac_14,aac_15,aac_16,aac_17,aac_18,aac_19,aac_20,uniprot_id
0,0.050420,0.016807,0.061983,0.035047,0.020833,0.054217,0.044610,0.063197,0.061321,0.040404,...,0.074468,0.022819,0.044702,0.044702,0.058201,0.021505,0.047187,0.055794,0.034483,B2MG_HUMAN
1,0.050420,0.050420,0.069421,0.018692,0.024306,0.060241,0.074349,0.084906,0.004717,0.050505,...,0.029787,0.046980,0.048013,0.057947,0.058201,0.032258,0.078040,0.072961,0.077586,EGFR_HUMAN
2,0.042017,0.075630,0.052893,0.058411,0.114583,0.042169,0.018587,0.042453,0.014151,0.070707,...,0.053191,0.045638,0.043046,0.058201,0.000000,0.043011,0.032668,0.017167,0.068966,HDAC3_HUMAN
3,0.058824,0.059504,0.010744,0.049065,0.055556,0.012048,0.078067,0.051887,0.037736,0.030303,...,0.085106,0.060403,0.021523,0.063492,0.047619,0.043011,0.018149,0.051502,0.056034,HMOX1_HUMAN
4,0.016807,0.049587,0.029752,0.051402,0.027778,0.054217,0.066914,0.037736,0.101010,0.010101,...,0.070213,0.009396,0.059603,0.026455,0.084656,0.021505,0.041742,0.128755,0.060345,IFNG_HUMAN

In [62]:
fp_aac = interactions.merge(aac, on='uniprot_id')
print(fp_aac.shape)
fp_aac.head()

(131036, 24)

,Unnamed: 0,uniprot_id,pubchemID,interaction,aac_1,aac_2,aac_3,aac_4,aac_5,aac_6,...,aac_11,aac_12,aac_13,aac_14,aac_15,aac_16,aac_17,aac_18,aac_19,aac_20
0,0,HDAC3_HUMAN,24853793,1,0.042017,0.07563,0.052893,0.058411,0.114583,0.042169,...,0.023739,0.053191,0.045638,0.043046,0.058201,0.0,0.043011,0.032668,0.017167,0.068966
1,1,HDAC3_HUMAN,11700059,1,0.042017,0.07563,0.052893,0.058411,0.114583,0.042169,...,0.023739,0.053191,0.045638,0.043046,0.058201,0.0,0.043011,0.032668,0.017167,0.068966
2,2,HDAC3_HUMAN,6918878,1,0.042017,0.07563,0.052893,0.058411,0.114583,0.042169,...,0.023739,0.053191,0.045638,0.043046,0.058201,0.0,0.043011,0.032668,0.017167,0.068966
3,3,HDAC3_HUMAN,2746,1,0.042017,0.07563,0.052893,0.058411,0.114583,0.042169,...,0.023739,0.053191,0.045638,0.043046,0.058201,0.0,0.043011,0.032668,0.017167,0.068966
4,4,HDAC3_HUMAN,467801,1,0.042017,0.07563,0.052893,0.058411,0.114583,0.042169,...,0.023739,0.053191,0.045638,0.043046,0.058201,0.0,0.043011,0.032668,0.017167,0.068966

In [63]:
fp_aac = fp_aac.merge(fp, on='pubchemID')
fp_aac = fp_aac.drop('Unnamed: 0', axis=1)
print(fp_aac.shape)
fp_aac.head()

(131036, 905)

,uniprot_id,pubchemID,interaction,aac_1,aac_2,aac_3,aac_4,aac_5,aac_6,aac_7,...,fp_871,fp_872,fp_873,fp_874,fp_875,fp_876,fp_877,fp_878,fp_879,fp_880
0,HDAC3_HUMAN,24853793,1,0.042017,0.075630,0.052893,0.058411,0.114583,0.042169,0.018587,...,0,0,0,0,0,0,0,0,0,0
1,EGFR_HUMAN,24853793,0,0.050420,0.050420,0.069421,0.018692,0.024306,0.060241,0.074349,...,0,0,0,0,0,0,0,0,0,0
2,RASH_HUMAN,24853793,0,0.016807,0.057025,0.039720,0.031250,0.054217,0.006024,0.055762,...,0,0,0,0,0,0,0,0,0,0
3,PGH2_HUMAN,24853793,0,0.067227,0.025620,0.063084,0.027778,0.065972,0.036145,0.074349,...,0,0,0,0,0,0,0,0,0,0
4,IL6_HUMAN,24853793,0,0.025210,0.050413,0.053738,0.004673,0.069444,0.126506,0.014870,...,0,0,0,0,0,0,0,0,0,0

In [64]:
fp_aac.to_csv('../data/train-fp-aac.csv', index=False)